# Generated by Django 4.1.2 on 2022-11-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_book_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя Автора"
            ),
        ),
    ]
