# Generated by Django 4.1.2 on 2023-05-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_book_readers_alter_book_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrelation",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Very bad"),
                    (1, "Bad"),
                    (1, "Ok"),
                    (1, "Good"),
                    (1, "Very good"),
                ],
                null=True,
            ),
        ),
    ]
