# Generated by Django 4.1.2 on 2023-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_userbookrelation_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Скидка в рублях",
                max_digits=7,
                null=True,
                verbose_name="Скидка",
            ),
        ),
    ]
