# Generated by Django 4.1.2 on 2023-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_book_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Скидка в рублях",
                max_digits=7,
                verbose_name="Скидка",
            ),
        ),
    ]
