# Generated by Django 4.1.2 on 2023-06-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_book_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, max_digits=3, null=True, verbose_name="Рейтинг"
            ),
        ),
    ]
